from syllabicator import Silabicador

syl = Silabicador()
result = syl("puchacay")
print("%s, %s" % (result[0], result[1]))
result = syl("y")
print("%s, %s" % (result[0], result[1]))
result = syl("hoy")
print("%s, %s" % (result[0], result[1]))
result = syl("rey")
print("%s, %s" % (result[0], result[1]))
result = syl("querida")
print("%s, %s" % (result[0], result[1]))
result = syl("alquimista")
print("%s, %s" % (result[0], result[1]))
result = syl("guey")
print("%s, %s" % (result[0], result[1]))
result = syl("cayn")
print("%s, %s" % (result[0], result[1]))
result = syl("adherir")
print("%s, %s" % (result[0], result[1]))
result = syl("hembra")
print("%s, %s" % (result[0], result[1]))
result = syl("perro")
print("%s, %s" % (result[0], result[1]))
result = syl("llevar")
print("%s, %s" % (result[0], result[1]))
result = syl("carretera")
print("%s, %s" % (result[0], result[1]))
result = syl("chicharrón")
print("%s, %s" % (result[0], result[1]))
result = syl("transgredir")
print("%s, %s" % (result[0], result[1]))
result = syl("instrucción")
print("%s, %s" % (result[0], result[1]))
result = syl("extrañamiento")
print("%s, %s" % (result[0], result[1]))
result = syl("entrega")
print("%s, %s" % (result[0], result[1]))
result = syl("espronceda")
print("%s, %s" % (result[0], result[1]))
result = syl("institución")
print("%s, %s" % (result[0], result[1]))
result = syl("constitución")
print("%s, %s" % (result[0], result[1]))
result = syl("premiación")
print("%s, %s" % (result[0], result[1]))
result = syl("transgresión")
print("%s, %s" % (result[0], result[1]))
result = syl("playas")
print("%s, %s" % (result[0], result[1]))
result = syl("playa")
print("%s, %s" % (result[0], result[1]))
result = syl("padres")
print("%s, %s" % (result[0], result[1]))
result = syl("calcificación")
print("%s, %s" % (result[0], result[1]))
result = syl("gimnasio")
print("%s, %s" % (result[0], result[1]))
result = syl("acróstico")
print("%s, %s" % (result[0], result[1]))
result = syl("atraen")
print("%s, %s" % (result[0], result[1]))
result = syl("seca")
print("%s, %s" % (result[0], result[1]))
result = syl("salón")
print("%s, %s" % (result[0], result[1]))
result = syl("mano")
print("%s, %s" % (result[0], result[1]))
result = syl("pena")
print("%s, %s" % (result[0], result[1]))
result = syl("supercalifragilisticoespiralidoso")
print("%s, %s" % (result[0], result[1]))
result = syl("escvla")
print("%s, %s" % (result[0], result[1]))
result = syl("estt")
print("%s, %s" % (result[0], result[1]))
